Category.create({name: "Traveling"})
Category.create({name: "Clothing"})
Category.create({name: "Taxi"})
Category.create({name: "Cafes"})
Category.create({name: "Shops"})
Category.create({name: "Other"})
